### ISSUE TITLE
Special chars in inputs

### ISSUE THREAD

**Issue by donall-factual** [Factual/drake#128]
I'm seeing an error when I try to run drake-HEW for the US, using command 
```
./scripts/run-poi-workflow us_v3_config_autobuild --name test_us_autobuild_iflow  --drakeify-iflow
```
Output:
```
3. Running iflow...
hew__jar_parameter=/home/donall/code/hadoop-extraction-workflow/scripts/../hadoop-extraction-workflow-hadoop.jar iflow -w /home/donall/code/hadoop-extraction-workflow/scripts/hew.d --name test_us_autobuild_iflow --jobs 2 --targetv ...
Clojure version: {:major 1, :minor 4, :incremental 0, :qualifier nil}
Options: {:help false, :tmpdir /home/donall/code/hadoop-extraction-workflow/scripts/.iflow/test_us_autobuild_iflow-info, :logfile /home/donall/code/hadoop-extraction-workflow/scripts/.iflow/test_us_autobuild_iflow-info/drake.log, :host 10.20.10.249, :auto false, :guava-event-bus #<EventBus com.google.common.eventbus.EventBus@6db4b903>, :empty-input-dir-valid true, :name test_us_autobuild_iflow, :vineyard false, :workflow /home/donall/code/hadoop-extraction-workflow/scripts/hew.d, :port 3000, :jobs 2, :targetv [...], :plugins plugins.edn}
iflow: illegal syntax starting with "&_Resorts_20130912.US.json," for step definition
```

I think the "&_Resorts" is part of a filename in HDFS and drake is interepreting the '&' as a special character. I'm not entirely sure if this is drake-HEW specific or not. If it is, I'm not sure which repo to put the ticket in...

**Comment by dirtyvagabond** [comment]
@donall-factual per my previous comment to you, i was asking you to use @amalloy 's fix, verify it worked, then close this ticket.

**Comment by donall-factual** [comment]
Sorry, I should have included a message. This has long been fixed.

**Comment by mavericklou** [comment]
@amalloy '&' is supported, but still space is not supported with single quote
![image](https://cloud.githubusercontent.com/assets/855457/7294611/5d6d7b62-e9e1-11e4-8120-4e8abc93baa2.png)

**Comment by amalloy** [comment]
Drake is working fine, but your shell command is not quoting the input, and
thus bash is breaking it on spaces. Try `"$INPUT"`. I think that would work
but can't test it now.

**Comment by mavericklou** [comment]
"$INPUT" works here. Thanks @amalloy 

P.S. I can understand that this might be the only thing we can do here, but still this is not so handy. If I know I have to quote my inputs and commands, this means I know what will be in the filename. But sounds like here we don't have any other solution to make this more transparent.

**Comment by amalloy** [comment]
You have to quote anything you would quote in bash. Really all drake does here is turn this step into the following simple bash script:

    INPUT="whatever filename with spaces"
    cat $INPUT

The drake step fails because that bash script fails: there is no special drake-specific issue here, you just have to know that what you are writing is interpreted by your shell.
