### ISSUE TITLE
Print some context when code inside of a drake step fails

### ISSUE THREAD

**Issue by morgan-mullaney** [Factual/drake#150]
```
.drake/ruby-a9c1abd94afc81f4428c5e97ef69a42b.bat:10:in `<main>': undefined method `merge' for nil:NilClass (NoMethodError)
```
It would be nice if drake also printed the contents of that temp file - I'm usually launching workflows via some automated process and would like to be able to debug straight from the log rather than ssh into the box running the workflow and hunt down the temp file.

(it's possible of course to look it up in the workflow file, but that requires you to mentally work out what line the error was actually on, and the values of any drake variables used in the block).

**Comment by dirtyvagabond** [comment]
ping @morgan-mullaney

**Comment by morgan-mullaney** [comment]
Yeah, the `:file` output is present, thanks
