### ISSUE TITLE
database protocol

### ISSUE THREAD

**Issue by potash** [Factual/drake#151]
It would be awesome if there was a database protocol. I often use a database for parts of my workflow and curretly I just use tags for those steps. What I'd imagine is the following:

```
psql://user@host/database/schema/table <- input.csv
    \COPY to $[SCHEMA].$[TABLE] from input.csv WITH CSV HEADER;
```

Unfortunately there is is no reliable way to get modification timestamps except with filesystem access to the system that the database is running on. Any advice from those of you that have used databases in a drake workflow?

See my other issue #152 for a potential workaround using transitive timechecks.

**Comment by justmytwospence** [comment]
It would be much nicer if Drake were able to, for example, check to see if a table had already been created instead of checking to see if some placeholder file had been created. I use Drake for managing a PostgreSQL/PostGIS workflow, and this would make it an order of magnitude more useful.
