### ISSUE TITLE
Distributed environment http support?

### ISSUE THREAD

**Issue by matanster** [Factual/drake#158]
Is there anything in drake that can invoke an http step through api rather than through `wget` and `curl`?

It would make drake more natural to use in a distributed setup, where some data gets prepared on other machines, and enable drake to orchestrate an execution environment that spreads across several servers through http rather than ssh, in a more idiomatic way.

Can it be accomplished at present, using any of the clojure http libraries in the wild, when using drake programmatically?

Thanks!

**Comment by dirtyvagabond** [comment]
hi @matanster Drake doesn't currently have out-of-the-box support for this. My best advice would be to offload this into a script and make that script be a discreet step
