### ISSUE TITLE
Remove Factual specific stuff from c4 protocol

### ISSUE THREAD

**Issue by dirtyvagabond** [Factual/drake#159]

**Comment by mavericklou** [comment]
97bbcd034f7bba5434697d8c7904107a26988904

**Comment by mavericklou** [comment]
Done. Also cleanup dependencies.
 * Upgrade to clojure 1.6.0.
 * Remove useless dependencies.
 * Upgrade csv lib to latest stable.
 * Upgrade chshire to same version in drake.
