### ISSUE TITLE
Update project.clj with dependencies for cdh5 compatibility

### ISSUE THREAD

**Issue by rishifactual** [Factual/drake#165]
@mavericklou 

With the migration to cdh5, the drake uberjar from source no longer interfaces with HDFS. Can you add the necessary dependencies to the project.clj to enable cdh5 compatibility? Thanks.

**Comment by dirtyvagabond** [comment]
@mavericklou please get an ETA to @rishifactual

**Comment by mavericklou** [comment]
@rishifactual we recently removed hadoop dependency from drake, so that people can choose hadoop version easily. Right now bin/drake script on develop branch will include hadoop classpath together with conf and all jars needed.

**Comment by dirtyvagabond** [comment]
This is the script Mav is talking about:
https://github.com/Factual/drake/blob/develop/bin/drake

It implies that your env specifies your desired Hadoop lib via $HADOOP_CLASSPATH.

@rishifactual does this move you forward?

**Comment by rishifactual** [comment]
Looks like everything is working. Thanks guys!

Closing the ticket, I will reopen if something else comes up re: drake and HDFS.

**Comment by rishifactual** [comment]
@mavericklou with [this line to determine the DRAKE_HOME](https://github.com/Factual/drake/blob/develop/bin/drake#L3), using ```dirname``` does not allow us to use a symlink to this script to invoke drake. Is there a better way for us to implement that line? Or, at the very least, can we check for the environment variable $DRAKE_HOME first? That way I can specify $DRAKE_HOME in my .bashrc and use a symlink.

**Comment by amalloy** [comment]
Just change it to `DRAKE_HOME=${DRAKE_HOME-$(dirname $(dirname $0))}`, to let you override the default behavior with an environment variable.

**Comment by rishifactual** [comment]
That sounds perfect. @mavericklou , can you do this since I don't have write privileges?

**Comment by dirtyvagabond** [comment]
@rishifactual i've done it with https://github.com/Factual/drake/commit/ba4f2ba0a638776987d6e26eb032483df73ced54

please verify & close, thanks!

**Comment by rishifactual** [comment]
Works perfectly, thanks!
