### ISSUE TITLE
create apt repository for easy drake installation

### ISSUE THREAD

**Issue by mavericklou** [Factual/drake#173]
We now has homebrew support for OS X
Need to support apt-get for Ubuntu

**Comment by amalloy** [comment]
Getting something into the stable debian repos is both difficult and time consuming. I certainly know how to do it myself. Creating our own ppa and publishing to that is probably easier, but I don't think asking users to add a ppa and use that is any easier for them than the current setup instructions.

**Comment by amalloy** [comment]
Certainly *don't* know how to do it myself, that is.

**Comment by mavericklou** [comment]
@amalloy I've added something into drake script that make it more like `lein` script. It downloads drake jar to ~/.drakerc folder and use it. Also 'drake upgrade' is supported now.

**Comment by dirtyvagabond** [comment]
@mavericklou so then i believe the correct action on this ticket is to close it as "won't fix", yeah?

**Comment by mavericklou** [comment]
@dirtyvagabond I think we can wait for everybody trying the new way of installation. If it turns out everyone is happy, yes, we will close this ticket as won't fix.

**Comment by mavericklou** [comment]
I bet no one will like a apt-get install solution after we have `drake upgrade`. Closing
