### ISSUE TITLE
Optional inputs not working?

### ISSUE THREAD

**Issue by chen-factual** [Factual/drake#179]
Example given in the [Drake Google doc](https://docs.google.com/document/d/1bF-OKNLIG10v_lMes_m4yyaJtAaJKtdK0Jizvi_MNsg/edit#) indicates a question mark before an input makes it optional:

```
Drakefile:

; Providing an optional synonym list to the command
output <- input_data, ?synonym_list, model_data
  # A sample command line
  # Playing a trick with variable expansion here (see Bash manual)
  echo INPUT2=$INPUT2
  echo “mytool $INPUT1 --model $INPUT3 ${INPUT2:+--synonyms $INPUT2}

```

In my workflow, I have:

```
workflow_meta.json <- train-results.json, ?metadata.json
  python scripts/workflow-meta.py \
    --training-results $INPUT1 \
    --misc-meta $INPUT2 \
    --output $OUTPUT
```

And I get the output:
```
drake: no input data found in locations: /home/chen/code/predict/workflow/resolve/test-dir/?metadata.json
```

I'm using a base directory, if that affects things. Is there something special I need to do if I'm using a base directory?

**Comment by dirtyvagabond** [comment]
@mavericklou please investigate. ideally you can add a test and fix

**Comment by amalloy** [comment]
@dirtyvagabond there's not much to investigate: the feature is colored red in the drake spec, which means "this feature doesn't exist".

This use of color-coding as the only way to tell the difference between features drake actually has and those that someone once hoped it could have has caused confusion many times. I'd recommend moving the "doesn't yet exist" feature list all to the bottom of the spec, under a heading that makes it clear they don't exist, or even to another document entirely, to be spliced into the real spec if anyone actually does implement those features. What do you think?

**Comment by dirtyvagabond** [comment]
my bad. for some reason i thought this had worked in the past. 

@amalloy i'm fine with either of your suggestions. you might want to run it by @aboytsov if you care to, or just do it. i'm happy either way.

@chen-factual , closing this as "won't fix -- missing feature that no one currently has planned to implement"

**Comment by chen-factual** [comment]
@dirtyvagabond 
Can I just implement it? I actually need this for a workflow I'm writing, and I'm strongly prefer to not have several if/elses everywhere.

**Comment by dirtyvagabond** [comment]
@chen-factual you're very welcome to implement! @amalloy, i'm Remote this week. you willing to offer guidance?

**Comment by amalloy** [comment]
Sure, I can answer questions.

**Comment by aboytsov** [comment]
Btw guys I'm on board with getting rid of color-coding - I've seen this confusion one too many times, too.
