### ISSUE TITLE
Drake thinks step doesn't have inputs

### ISSUE THREAD

**Issue by chen-factual** [Factual/drake#185]
Example output:
```
Using drip to start up JVM...
The following steps will be run, in order:
  1: %cv, /home/chen/code/predict/workflow/resolve/test-dir/internal/cv-predictions.json, /home/chen/code/predict/workflow/resolve/test-dir/internal/cv-results.json <- /home/chen/code/predict/workflow/resolve/test-dir/features.json, /home/chen/code/predict/workflow/\
resolve/test-dir/params.json.example [no-input step]
```

I already have output data for this particular step, so I expected it to not be re-run. However, here Drake doesn't recognize input files and this thinks this is a no-input step, and thus will erroneously always try to run this step.

**Comment by amalloy** [comment]
That step is tagged, with `%cv`. If you do something like `drake %cv`, it should rebuild the `%cv` step regardless of its output freshness, right? It certainly looks like an error that it calls it a no-input step, but without seeing your drakefile and command line it's not necessarily an error to rerun the step.

**Comment by chen-factual** [comment]
I have a wrapper script, but essentially what I'm running is:
```
drake --base $BASE_DIR
```

**Comment by tknuth** [comment]
I reinstalled drake and recognised the same behaviour. Is it a bug in a new version?

**Comment by tknuth** [comment]
I tested this with https://github.com/Factual/drake/releases/tag/v0.1.7 and the bug does not appear. Must have been introduced in 1.0.0 or 1.0.1.

**Comment by dirtyvagabond** [comment]
@tknuth would you mind sharing the portion of your workflow that demos this bug, and the exact drake command you're using?

**Comment by chen-factual** [comment]
Here's the simplest way to reproduce this:

Drakefile:
```
file2 <- file1
  cp $INPUT $OUTPUT
```

Missing output, as expected
```
~/code/drake $ touch file1
~/code/drake $ lein run -w Drakefile
The following steps will be run, in order:
  1: /home/chen/code/drake/file2 <- /home/chen/code/drake/file1 [missing output]
Confirm? [y/n]
```

Now if we add file2, either via the script or alternative means:
```
~/code/drake $ lein run -w Drakefile
The following steps will be run, in order:
  1: /home/chen/code/drake/file2 <- /home/chen/code/drake/file1 [no-input step]
Confirm? [y/n] y
```

**Comment by amalloy** [comment]
Okay, so the tag thing is a total red herring then, right? It's just "steps are run whether or not they need to be run, because they look like no-input steps"? That is a pretty big deal.

**Comment by chen-factual** [comment]
Yeah, I mentioned in an earlier comment the tag is inconsequential.

> I have a wrapper script, but essentially what I'm running is:
```
drake --base $BASE_DIR
```


Where you can clearly see no tag is used.

**Comment by amalloy** [comment]
Okay, this is pretty easy to reproduce, as @chen-factual said. I'll start debugging it.

**Comment by amalloy** [comment]
@chen-factual You brought this one on yourself! (but it was my fault too). Your optional-inputs stuff had some incorrect destructuring in it, which I think was probably because of a renaming I suggested you do. Anyway it is fixed now.

**Comment by chen-factual** [comment]
Thanks for cleaning up my mess @amalloy :)

I should've dug into this earlier instead of just working around it.
