### ISSUE TITLE
Error: Could not find or load main class drake.core

### ISSUE THREAD

**Issue by toomanycats** [Factual/drake#186]
This is my first time trying Drake. I cloned the repo and switched to the Master branch.
java -version yields: 

java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

drake -h
Using DRAKE_HOME: /home/daniel/drake

========= UBERJAR COMPILING =========
/home/daniel/drake/bin/drake: line 68: lein: command not found
========= UBERJAR COMPILED ==========

Error: Could not find or load main class drake.core

I get the feeling I'm missing something very fundamental. :|

**Comment by amalloy** [comment]
If you're going to build it from source, you need `leiningen`, the Clojure build tool, installed. If instead you follow the steps in the readme, the drake script will just download a prebuilt jar for you.

**Comment by dirtyvagabond** [comment]
@toomanycats the easiest way to get Drake is to use Homebrew if you're on a Mac, or the drake script as Alan mentioned if you're on Linux. What's your OS and do you have a reason to want to build from source?

**Comment by toomanycats** [comment]
Hello all and thank you for responding.
I run Ubuntu 14.04.
Should have noted all this before was just a late night...
Here's what I tried first off before anything else. 

I cloned the repo, switched to the master branch, stepped into the bin dir and ran the script there:

./drake
Downloading drake jar for version 1.0.1...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
ERROR: Failed to download https://github.com/Factual/drake/releases/download/1.0.1/drake.jar with exit code 77


Cheers

**Comment by toomanycats** [comment]
Was reading through the script, added a -x for debug mode:
Here's the output again in debug mode:

./drake
+ '[' '' = '' ']'
+ type -p curl
+ '[' '' '!=' '' ']'
+ HTTP_CLIENT='curl  -f -L -o'
+ DRAKE_VERSION=1.0.1
+ DRAKE_SCRIPT_URL=https://raw.githubusercontent.com/Factual/drake/master/bin/drake
+ DRAKE_URL=https://github.com/Factual/drake/releases/download/1.0.1/drake.jar
+ DRAKE_TMP_SCRIPT=/tmp/drake_script.sh.tmp
+ '[' '' = --upgrade ']'
+ '[' -z ']'
++ which hadoop
+ [[ -n '' ]]
+ '[' '' = --hadoop-version ']'
+ '[' -z ']'
+ DRAKE_SCRIPT_PATH=./drake
+ '[' -L ./drake ']'
+++ dirname ./drake
++ dirname .
+ DRAKE_HOME=.
+ '[' '!' -z x ']'
+ '[' -d . ']'
+ '[' -f ./project.clj ']'
+ DRAKE_HOME=/home/daniel/.drakerc
+ mkdir -p /home/daniel/.drakerc/jar
+ DRAKE_JAR=/home/daniel/.drakerc/jar/drake-1.0.1-standalone.jar
+ '[' '!' -f /home/daniel/.drakerc/jar/drake-1.0.1-standalone.jar ']'
+ echo 'Downloading drake jar for version 1.0.1...'
Downloading drake jar for version 1.0.1...
+ echo ''

+ curl -f -L -o /home/daniel/.drakerc/jar/drake-1.0.1-standalone.jar.tmp https://github.com/Factual/drake/releases/download/1.0.1/drake.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
+ exit_code=77
+ '[' 77 -ne 0 ']'
+ echo 'ERROR: Failed to download https://github.com/Factual/drake/releases/download/1.0.1/drake.jar with exit code 77'
ERROR: Failed to download https://github.com/Factual/drake/releases/download/1.0.1/drake.jar with exit code 77
+ exit 1

**Comment by toomanycats** [comment]
Well I got tired of trying to fix the SSL cert and just used "insecure" connection...

However there's a new error:

+ echo 'Drake jar downloaded for version 1.0.1.'
Drake jar downloaded for version 1.0.1.
+ '[' '' = --version ']'
++ which drip
+ [[ -n '' ]]
+ java -cp :/home/daniel/.drakerc/jar/drake-1.0.1-standalone.jar drake.core
drake: cannot find file or directory: /home/daniel/drake/bin/./Drakefile (use --help for documentation)


Sure enough, I can't find that file anywhere...but not sure that's a real installation failure...going to try the demos.

**Comment by mavericklou** [comment]
@toomanycats well I guess you just fixed all your issues. This message "drake: cannot find file or directory: /home/daniel/drake/bin/./Drakefile" indicates that drake can not find any Drakefile to run in current working directory. So the point is, this drake script is both self-install script and running script. This is following the same design of leiningen.

**Comment by toomanycats** [comment]
Hello,

Thank you for replying and taking time for my issue.

I still have some problems.

I went to the demo directory and tried to run a demo and again, received
the drake.core not found error.

Although I'd like to believe that this is my fault somehow..

I'll try again and post details asap.

Cheers !

--
  Daniel P Cuneo
  dpcuneo@fastmail.fm
 
 
 
On Mon, Jul 27, 2015, at 02:37 AM, Maverick Lou wrote:
> @toomanycats[1] well I guess you just fixed all your issues. This message "drake: cannot find file or directory: /home/daniel/drake/bin/./Drakefile" indicates that drake can not find any Drakefile to run in current working directory. So the point is, this drake script is both self-install script and running script. This is following the same design of leiningen.


> —
> Reply to this email directly or view it on GitHub[2]. 


>  
 


Links:

  1. https://github.com/toomanycats
  2. https://github.com/Factual/drake/issues/186#issuecomment-125146570
