### ISSUE TITLE
new install drake.core not found

### ISSUE THREAD

**Issue by toomanycats** [Factual/drake#190]
Hello everyone and thank you in advance for you help.

**Some details about my setup**
>java -version
>java version "1.7.0_80"
>Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
>Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

>uname -a
>Linux geek 3.16.0-45-generic #60~14.04.1-Ubuntu SMP Fri Jul 24 21:16:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Previously**
I posted here previously b/c the Linux installer script wasn't working for me.
Initially, I cloned the drake repo b/c that's just kinda what I do and the link to the installer script was not obvious using the browser theme I have.

It shouldn't really matter right, because I got the bin dir and the installer  with the clone.
The installer failed for my Ubuntu 14.04 I think b/c of where Ubuntu keeps the SSL components.

Since then then, I  got my Drake installation a little closer to working by simply using an insecure download option with cURL.

**Where I'm at now**
I step into the drake directory and do this:
bin/drake
>Using DRAKE_HOME: .
>
>========= UBERJAR COMPILING =========
>Copying 90 files to /home/daniel/drake/lib
>Compiling drake.core
>Compiling drake.clj-frontend
>Compiling drake.clj-frontend-utils
>Compiling drake.core
>Compiling drake.event
>Compiling drake.fs
>Compiling drake.options
>Compiling drake.parser
>Compiling drake.parser_utils
>Compiling drake.plugins
>Compiling drake.protocol
>Compiling drake.protocol-c4
>Compiling drake.protocol-eval
>Compiling drake.protocol-interpreters
>Compiling drake.protocol-test
>Compiling drake.shell
>Compiling drake.stdin
>Compiling drake.steps
>Compiling drake.utils
>Compiling drake.viz
>Compilation succeeded.
>Created /home/daniel/drake/drake-1.0.1.jar
>Including drake-1.0.1.jar
Including sisu-guice-3.0.3-no_aop.jar
>Including tools.macro-0.1.1.jar
>Including wagon-http-shared4-2.2.jar
>Including aws-java-sdk-1.7.5.jar
>Including aether-connector-wagon-1.13.1.jar
>Including guava-14.0.1.jar
>Including ordered-1.3.1.jar
>Including commons-httpclient-3.0.1.jar
>Including oro-2.0.8.jar
>Including aether-connector-file-1.13.1.jar
>Including wagon-http-2.2.jar
>Including fnparse-2.3.0.jar
>Including jets3t-0.7.1.jar
>Including tigris-0.1.1.jar
>Including plexus-component-annotations-1.5.5.jar
>Including drake-interface-0.0.1.jar
>Including cheshire-5.2.0.jar
>Including commons-net-1.4.1.jar
>Including maven-aether-provider-3.0.4.jar
>Including commons-el-1.0.jar
>Including plexus-utils-2.0.7.jar
>Including jlk-time-0.1.jar
>Including jetty-6.1.14.jar
>Including jlk-utility-0.1.jar
>Including tools.logging-0.2.3.jar
>Including sosueme-0.0.15.jar
>Including sisu-inject-plexus-2.2.3.jar
>Including core.cache-0.6.3.jar
>Including jasper-runtime-5.5.12.jar
>Including commons-io-2.0.1.jar
>Including jsp-api-2.1-6.1.14.jar
>Including plexus-classworlds-2.4.jar
>Including xmlenc-0.52.jar
>Including fs-1.3.2.jar
>Including aether-util-1.13.1.jar
>Including snakeyaml-1.5.jar
>Including core-3.1.1.jar
>Including useful-0.7.6-alpha1.jar
>Including jackson-core-2.2.1.jar
>Including commons-codec-1.6.jar
>Including jsoup-1.6.1.jar
>Including ant-1.6.5.jar
>Including clojure-csv-2.0.1.jar
>Including jsp-2.1-6.1.14.jar
>Including log4j-1.2.16.jar
>Including maven-repository-metadata-3.0.4.jar
>Including junit-4.5.jar
>Including slingshot-0.10.3.jar
>Including clj-logging-config-1.9.6.jar
>Including core.memoize-0.5.6.jar
>Including clj-time-0.6.0.jar
>Including clj-yaml-0.4.0.jar
>Including hadoop-core-0.20.2.jar
>Including algo.monads-0.1.0.jar
>Including data.priority-map-0.0.2.jar
>Including rhizome-0.2.5.jar
>Including pomegranate-0.2.0.jar
>Including jackson-annotations-2.1.1.jar
>Including httpcore-4.1.2.jar
>Including clojure-1.6.0.jar
>Including jackson-dataformat-smile-2.2.1.jar
>Including kfs-0.3.jar
>Including servlet-api-2.5-6.1.14.jar
>Including dynapath-0.2.3.jar
>Including jackson-databind-2.1.1.jar
>Including c4-0.2.1.jar
>Including jetty-util-6.1.14.jar
>Including hdfs-clj-0.1.3.jar
>Including swank-clojure-1.3.2.jar
>Including sisu-inject-bean-2.2.3.jar
>Including maven-model-builder-3.0.4.jar
>Including tools.reader-0.7.2.jar
>Including aether-spi-1.13.1.jar
>Including commons-logging-1.0.3.jar
>Including aether-api-1.13.1.jar
>Including commons-compress-1.3.jar
>Including httpclient-4.2.jar
>Including java-getopt-1.0.13.jar
>Including useful-0.11.3.jar
>Including maven-model-3.0.4.jar
>Including wagon-provider-api-2.2.jar
>Including hsqldb-1.8.0.10.jar
>Including clj-aws-s3-0.3.10.jar
>Including jasper-compiler-5.5.12.jar
>Including aether-impl-1.13.1.jar
>Including joda-time-2.0.jar
>Including clojopts-0.3.4.jar
>Including plexus-interpolation-1.14.jar
>Including commons-cli-1.2.jar
>Including digest-1.4.0.jar
>Created /home/daniel/drake/drake.jar
>========= UBERJAR COMPILED ==========
>
>Error: Could not find or load main class drake.core

**Comment by amalloy** [comment]
Are you committed to building this from source? As I said in your last issue, if you delete sour source checkout and just use the installer script, you will get a pre-built jar. There's nothing wrong with building from source, of course, but you seem to be running into some issues.

**Comment by toomanycats** [comment]
Sorry to be a pain amalloy. I suppose I'm confused. I'm not committed to building from source.
I just haven't had success.

Would  you please confirm the steps using only the installer.
I assume it's very simple, download installer script, run it. 
In my case, I edit the script to not try to use the ssl stuff with cURL.
Then what exactly should happen next ?

Thanks again...cheers
tmc

**Comment by amalloy** [comment]
The installer script is also the launcher script: it self-installs. Once you have it, you can run drake as described in the readme, by writing a Drakefile that defines the steps to run to manipulate whatever data you have.

**Comment by toomanycats** [comment]
I dunno what I did wrong the last time....but it all appears to work as expected now...
I started from scratch and just downloaded the installed script and ran it. I cloned the repo for the demos and ran drake on the demos and it works...

I suppose you can just delete this thread as it might just be confusing since I can't recreate the error

**Comment by lauralorenz** [comment]
Just for anyone who also googles this... I think I had the same problem. The directions on the README "Download the drake script from the master branch of this project." seemed to me not to preclude just git cloning the entire repo, so I did that to download the drake script and then followed along the rest of the directions. But confusingly the install script will throw these errors @toomanycats experienced if you clone the entire repo, but not if you have the install script alone. You have to take it literally and download ONLY the install script at `master:bin/drake` and not the rest of the repo. Then it will install properly. 

For example this is what I did on ubuntu 14.04:

``` bash
apt-get update && apt-get install -y default-jre # install java
# DO NOT git clone the entire repo. 
#instead, just get the single install script with wget or whatever you like 
# put the file wherever you want to put it that will be on your PATH
wget https://raw.githubusercontent.com/Factual/drake/master/bin/drake -O /bin/drake # get install script `master:bin/drake` 
chmod 755 /bin/drake # set permissions
drake # first run of drake script will install
```
