### ISSUE TITLE
real-time stdout from a python step

### ISSUE THREAD

**Issue by potash** [Factual/drake#199]
When executed via drake, python stdout seems to be delayed until step completion. For example I have the following two seemingly equivalent scripts in python and bash:

```
import time

print 'hello'
time.sleep(2)
print 'world'
```

```
echo hello
sleep 2
echo world
```

When the first script is run with drake I don't see any output until the step completes, while the second one shows output in real-time. Is this something subtle about the way python handles stdout? How can I fix it? Thanks.

**Comment by potash** [comment]
Ah, the answer is that by default python buffers output. The most convenient way to disable this in the context of a drake workflow is by setting the PYTHONUNBUFFERED environment variable. See this [thread](http://stackoverflow.com/questions/107705/disable-output-buffering) for more details.

**Comment by chen-factual** [comment]
Thanks for figuring this out, I have some long running tasks that spit out output only in chunks and I was curious about that.
