### ISSUE TITLE
$BASE does not get prepended on %included workflow

### ISSUE THREAD

**Issue by potash** [Factual/drake#200]
According to the documentation
> %include behaves exactly as if the included file was physically inserted at the point of the inclusion
but here is a counter-example. Let `aux/input` be an input file.This Drakefile works:

```
BASE=aux
output <- input
    cat $INPUT > $OUTPUT
```

But these two do not:
Drakefile:
```
BASE=aux
%include Drakefile2
```

Drakefile2:

```
output <- input
   cat $INPUT > $OUTPUT
```

However if I modify Drakefile2 to explicitly use the $BASE prefix it works again:

```
$[BASE]/output <- $[BASE]/input
    cat $INPUT > $OUTPUT
```

This is puzzling because if $BASE is present why isn't it getting prepended?

**Comment by chen-factual** [comment]
Hi Eric, I couldn't reproduce this behavior using the latest Drake (i.e. head of develop). Can you please provide some versioning information?

**Comment by potash** [comment]
Hi Chen, thanks you're right it works with the latest version. However I now have a very thorny issue #201
