### ISSUE TITLE
1.0.3 jar not found

### ISSUE THREAD

**Issue by potash** [Factual/drake#212]
The drake binary doesn't work since the 1.0.3 release because the [jar](https://github.com/Factual/drake/releases/download/1.0.3/drake.jar) does not exist.

**Comment by TheDahv** [comment]
Pinned to previous commit in our Docker build script until then:

```
ADD https://raw.githubusercontent.com/Factual/drake/17f1f1a57b40ec04ab1b49112b8ad1a7c6128e18/bin/drake /usr/local/bin/drake
RUN chmod +x /usr/local/bin/drake

# Drake downloads the JAR the first time it's invoked.
RUN /usr/local/bin/drake --help > /dev/null
```

**Comment by dirtyvagabond** [comment]
Apologies for this. I've fixed by renaming the release to be consistent with the previous naming conventions. The normal jar link is thereby fixed:
https://github.com/Factual/drake/releases/download/1.0.3/drake.jar

@potash and @TheDahv , is that good?

**Comment by potash** [comment]
Yup, thanks @dirtyvagabond
