### ISSUE TITLE
Don't depend on HADOOP_CLASSPATH if it is set and the hadoop command exists

### ISSUE THREAD

**Issue by manuel-factual** [Factual/drake#213]
This code https://github.com/Factual/drake/blob/develop/bin/drake#L45-L50 sets `HADOOP_CLASSPATH` to the result of `hadoop classpath` only if `HADOOP_CLASSPATH` is not already set. This is a problem for drake when `HADOOP_CLASSPATH` is set to user extra libraries, since the `HADOOP_CLASSPATH` will not include core hadoop libraries and configurations.

`hadoop classpath` will already give you the combination of core hadoop + the extras in `HADOOP_CLASSPATH`. My suggestion is to not even check for the existence of `HADOOP_CLASSPATH`.

```
if [[ `which hadoop` ]]; then
    HADOOP_CLASSPATH=`hadoop classpath 2>/dev/null`
    HADOOP_VERSION=`hadoop version | head -1`
fi
```

**Comment by dirtyvagabond** [comment]
@manuel-factual maybe let's touch base in person, then a pr?
