### ISSUE TITLE
drake install problem

### ISSUE THREAD

**Issue by breezymri** [Factual/drake#216]
Hi I tried to follow the installation guide but ended up an error. When I run "drake" from the terminal after downloading it, it says the following:
....
Drake jar downloaded for version 1.0.3.
drake: cannot find file or directory: /home/breezymri/./Drakefile (use --help for documentation)

**Comment by dirtyvagabond** [comment]
hi @breezymri have you used Drake before? Please note that you need to point Drake to a valid Drakefile, which specifies your workflow. Could the problem be that you don't have a Drakefile? If so, this might be of some help:
https://github.com/Factual/drake/wiki/Tutorial#your-very-first-workflow
