### ISSUE TITLE
LICENSE 

### ISSUE THREAD

**Issue by Adrianzo** [Factual/drake#224]
Could you please specify the actual license?

IANAL but, not having the LICENSE file all these is just under strict copyright law. That means that we're only allowed to see, compile and run the code.

GitHub should state that pull requests are actually illegal when there's no LICENSE file. Actually, even before the PR (the actual edit in a simple text editor is a felony AFAIK).

Please consider licensing under a free software license, like GPL-3.

//edit: part of this message is intended as a joke over reality, please disregard if any comment in it seems inappropiate.

**Comment by chen-factual** [comment]
@dirtyvagabond 
Aaron any thoughts on this? IMO the big decision here is a GPL style license vs a more liberal one, and from there I don't think the legal nuances matter enough for us to care which variant in a group we use.

**Comment by dirtyvagabond** [comment]
@Adrianzo there is a [COPYING](https://github.com/Factual/drake/blob/develop/COPYING) file in the repo, which serves this purpose (this is mentioned at the bottom of the README, where licensing info is generally referenced). 

___tl;dr___: Eclipse Public License

Does this clear things up?
