### ISSUE TITLE
Make --vars processing more robust

### ISSUE THREAD

**Issue by myronahn** [Factual/drake#97]
Right now Drake uses a naive algorithm to split the `--vars` parameter on commas, not taking into account commas within quotes, nor providing a way to escape commas.  This makes it difficult to pass in variables such as:

```
ZOOKEEPER_QUORUM=zoo1,zoo2,zoo3
JSON={"p1":"v1","p2":"v2"}
```

I propose the following:
- Allow the user to pass in an arbitrary regular expression for splitting the `--vars` string.
- Default to a regex that will split on commas, but not commas within double-quotes.

NOTE: this is not as much a problem for shell usage, since we can use shell variables instead of passing it in via the `--vars` parameter.  For calling Embedded Drake #58  from Java this is a more important issue.

**Comment by mavericklou** [comment]
@amalloy I tried this feature today and it failed for me.
![image](https://cloud.githubusercontent.com/assets/855457/7294211/9882ea42-e9dd-11e4-8eb7-06b14a3f462f.png)

**Comment by amalloy** [comment]
As mentioned in the comments on this issue and (as I recall) in the help spec, the flag that's repeatable is --var, not --vars.

**Comment by dirtyvagabond** [comment]
maybe we can detect that up-front and error out, telling the user, "get your vars straight!" ?

or support repeatable vars as well?

**Comment by mavericklou** [comment]
Thanks @amalloy for point out the mistake. --var is working.
